services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: patata
      MYSQL_DATABASE: CarpetasBD
      MYSQL_USER: pablo
      MYSQL_PASSWORD: patata
    ports:
      - 3333:3306